# ReMarkable 2 supports black/gray0, gray1, gray1, gray2, gray3, gray4, gray5, gray6, gray07, gray8, gray9, gray10, gray11, gray12, gray13,gray14, white/gray15

calendars:
  - name: Personal
    source: calendars/personal.ics
    color: gray6
  - name: US Holidays
    source: https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/holidays.ics
    color: gray4
